# Generated by Django 3.0.8 on 2020-07-23 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tests.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название теста')),
                ('code', models.CharField(default=tests.helpers.random_code, max_length=5, verbose_name='Код')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('total_points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('points', models.IntegerField(default=0, verbose_name='Количество баллов за вопрос')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, verbose_name='Текст')),
                ('is_correct', models.BooleanField(verbose_name='Корректность')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Question', verbose_name='Вопрос')),
            ],
        ),
    ]
