# Generated by Django 3.0.8 on 2020-07-14 08:56

from django.db import migrations, models
import tests.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответ')),
                ('points', models.IntegerField(default=0, verbose_name='Количество баллов за вопрос')),
                ('with_options', models.BooleanField(verbose_name='С вариантами ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название теста')),
                ('evaluated', models.BooleanField(verbose_name='Оцениваемый')),
                ('questions_quantity', models.IntegerField(verbose_name='Количество вопросов')),
                ('passed_quantiry', models.IntegerField(verbose_name='Количество прошедших')),
                ('code', models.CharField(default=tests.helpers.random_code, max_length=5, verbose_name='Код')),
            ],
        ),
    ]
