# Generated by Django 3.0.8 on 2020-07-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_u'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U',
        ),
    ]
