# Generated by Django 3.0.8 on 2020-07-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20200720_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
