# Generated by Django 3.0.8 on 2020-07-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20200720_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='with_options',
        ),
        migrations.RemoveField(
            model_name='test',
            name='passed_quantity',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions_quantity',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('total_points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, verbose_name='Текст')),
                ('is_correct', models.BooleanField(verbose_name='Корректность')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Question', verbose_name='Вопрос')),
            ],
        ),
    ]
