# Generated by Django 3.0.8 on 2020-07-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20200721_0822'),
        ('tests', '0010_auto_20200720_1606'),
    ]

    operations = [
    ]
