# Generated by Django 3.0.8 on 2020-07-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_merge_20200721_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='active',
        ),
    ]
