# Generated by Django 3.0.8 on 2020-07-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_remove_test_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='evaluated',
        ),
    ]
